Feat/front
valter-junior/todolist pull request #5
Opened 2021-04-20 13:46 UTC by valter-junior

Review

2021-04-20 15:11 UTC, jfmrm requested changes

2021-04-20 15:11 UTC, jfmrm commented on front/src/App.js
> +export default App;
add empty line on the file end

2021-04-20 15:11 UTC, jfmrm commented on front/src/App.js
> +
remove this blank space

2021-04-20 15:11 UTC, jfmrm commented on front/src/App.js
> +
here too

2021-04-20 15:11 UTC, jfmrm commented on front/src/App.js
> +
here too

2021-04-20 15:11 UTC, jfmrm commented on front/src/App.js
> +
here too

2021-04-20 15:11 UTC, jfmrm commented on front/src/auth.js
> +export default new Auth();
add empty line

2021-04-20 15:11 UTC, jfmrm commented on front/src/home.js
> +
remove empty line

2021-04-20 15:11 UTC, jfmrm commented on front/src/home.js
> +    </div>
needs to be indented

2021-04-20 15:11 UTC, jfmrm commented on front/src/index.js
> +reportWebVitals();
add empty line

2021-04-20 15:11 UTC, jfmrm commented on front/src/login/login.js
> +export default Login;
add empty line

2021-04-20 15:11 UTC, jfmrm commented on front/src/login/login.js
> +
remove blank spaces

2021-04-20 15:11 UTC, jfmrm commented on front/src/login/sign.in.js
> +
remove empty lines

2021-04-20 15:11 UTC, jfmrm commented on front/src/login/sign.in.js
> +export default SignIn;
add empty line

2021-04-20 15:11 UTC, jfmrm commented on front/src/protected.route.js
> +}
add empty line

2021-04-20 15:11 UTC, jfmrm commented on front/src/protected.route.js
> +        }/>
fix indentation

2021-04-20 15:14 UTC, jfmrm commented
Now its compiling, nice job!

2021-04-20 15:16 UTC, jfmrm commented
one question: why have you used BrouserRouter on the index.js file?

2021-04-20 17:38 UTC, valter-junior commented
> one question: why have you used BrouserRouter on the index.js file?

I'm not right about this but  I used this component in file index.js to render my function with route written in file App.js and I forget fix it

2021-04-22 12:01 UTC, jfmrm requested changes

2021-04-22 12:01 UTC, jfmrm commented on front/src/home.js
> +        </div>
still not indented right do it like this:
```suggestion
              <h1>Task</h1>
              <Button 
                  onClick={() => {
                      auth.login(() => {
                          history.push("/login")       
                      });
                  }}>Login</Button>
              <Button component={Link} to="/sign-in">Sign In</Button>
          </div>
```

2021-04-22 12:01 UTC, jfmrm commented on front/src/protected.route.js
> +
```suggestion
              if(auth.isAuthenticated()) {
                  return <Component {...props}/>
              } else {
                  return (
                      <Redirect to={{
                          pathname: "/",
                          state: {
                              from: props.location
                         }}
                      }/>
                  )
             }   
```

2021-04-22 12:01 UTC, jfmrm commented on front/src/App.js
> +      </Container>
where is the Browser Router?

2021-04-22 13:36 UTC, valter-junior commented
Changes done

2021-04-22 14:38 UTC, jfmrm requested changes

2021-04-22 14:38 UTC, jfmrm commented on front/src/home.js
> +    )
```suggestion
    return (
       <div>
         <h1>Task</h1>
           <Button 
              onClick={() => {
                auth.login(() => {
                    history.push("/login")       
                });
              }}>Login</Button>
           <Button component={Link} to="/sign-in">Sign In</Button>
       </div>
    )
```

2021-04-22 14:38 UTC, jfmrm commented on front/src/index.js
> +  </BrowserRouter>,
should be React.StrictMode here.

BrowserRouter is already defined inside App

2021-04-22 16:59 UTC, valter-junior commented
Done

2021-04-23 12:03 UTC, jfmrm approved these changes

2021-04-23 14:44 UTC, merged